### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DcNdrew** [codetaylor/advancedmortars#14]
https://pastebin.com/nBk1E0ry
I did nothing but walked to my camp where isn't any mortar.

**Comment by nmarshall23** [comment]
How far away is the mortar? More than 160 meters? Does it happen every time you walk away from your camp?

**Comment by DcNdrew** [comment]
There isn't any kind of mortar.

**Comment by codetaylor** [comment]
I can't reproduce this, but I put a null check in that should prevent this from happening if `minecraft.objectMouseOver` happens to be null.

**Comment by codetaylor** [comment]
Should be fixed in next build. :)

**Comment by DcNdrew** [comment]
The crash is still on. I removed Advanced Mortars and everything is right.

**Comment by codetaylor** [comment]
Can I get the new crash report please?

**Comment by DcNdrew** [comment]
https://pastebin.com/tiSjASKC

**Comment by DcNdrew** [comment]
I don't know but could this be related to Better With Mods? It has a millstone which can make bonemeal.

**Comment by codetaylor** [comment]
Thanks for the crash report. :)

No, this has nothing to do with any other mod. This was another NPE occurring in a different place in the code for exactly the same reason as the first crash. Both have been fixed and shouldn't occur again.

If you do get another crash, please feel free to start a new issue. :)

Fixed in 1.3.9
